package com.dante.subjects.config;

import com.crawljax.core.configuration.CrawlRules;
import com.crawljax.core.configuration.CrawljaxConfiguration;
import com.crawljax.core.configuration.Form;
import com.crawljax.core.configuration.InputSpecification;
import com.crawljax.core.state.Identification;
import com.crawljax.forms.FormInput;
import com.crawljax.stateabstractions.visual.imagehashes.DHashStateVertexFactory;
import com.dante.subjects.ApplicationNames;
import com.dante.subjects.Config;
import com.dante.suitegenerator.SuiteGeneratorConfig;
import com.dante.tedd.extraction.DependencyGraphExtractionConfig;
import com.dante.utils.Properties;

/**
 * The application phoenix is NON DETERMINISTIC. In particular the order in which the boards are listed in the menu
 * is random. This will break the test suite generated by the crawler unless the application behaviour is changed. For
 * now I changed the generated test suite in order to cope with non determinism.
 * */
public class PhoenixConfig extends Config {

    private static final String url = "http://localhost:4000";
    private static final int waitTimeAfterReload = 1000;

    public PhoenixConfig() {
        super(ApplicationNames.Name.PHOENIX.getName());
    }

    @Override
    public CrawljaxConfiguration.CrawljaxConfigurationBuilder getCrawljaxConfig() {

        CrawljaxConfiguration.CrawljaxConfigurationBuilder builder = this.crawljaxCommonConfig(url,
                Properties.MAX_RUNTIME, 1000, waitTimeAfterReload);

//        builder.setConsiderCandidateElementsOnce(CrawljaxConfiguration.CandidateElementsMode.checked);
        builder.setConsiderCandidateElementsOnce(CrawljaxConfiguration.CandidateElementsMode.fired);

        builder.setStateVertexFactory(new DHashStateVertexFactory());

        builder.crawlRules().setCrawlPriorityMode(CrawlRules.CrawlPriorityMode.RANDOM);

        builder.crawlRules().click("a", "button");

        // board
        builder.crawlRules().click("div")
                .withAttribute("class", "board add-new");
        // list
        builder.crawlRules().click("div")
                .withAttribute("class", "list add-new");
        // created boards and lists
        builder.crawlRules().click("div")
                .withAttribute("class", "inner");
        // created card
        builder.crawlRules().click("div")
                .withAttribute("class", "card-content");
        // delete card
        builder.crawlRules().click("i")
                .withAttribute("class", "fa fa-trash-o");

        // trello website
        builder.crawlRules().dontClick("a")
                .withAttribute("href", "https://trello.com");
        // diacode website
        builder.crawlRules().dontClick("a")
                .withAttribute("href", "https://diacode.com");
        // twitter handle
        builder.crawlRules().dontClick("a")
                .withAttribute("href", "https://twitter.com/bigardone");

//        builder.crawlRules().dontClick("a")
//                .withAttribute("href","/sign_up");

        InputSpecification inputSpecification = new InputSpecification();

        Form signInForm = new Form();
        FormInput usernameInput = signInForm.inputField(FormInput.InputType.EMAIL,
                new Identification(Identification.How.xpath,
                        "/html[1]/body[1]/main[1]/div[1]/div[1]/main[1]/form[1]/div[1]/input[1]".toUpperCase()));
        usernameInput.inputValues("john@phoenix-trello.com");
        FormInput passwordInput = signInForm.inputField(FormInput.InputType.PASSWORD,
                new Identification(Identification.How.xpath,
                        "/html[1]/body[1]/main[1]/div[1]/div[1]/main[1]/form[1]/div[2]/input[1]".toUpperCase()));
        passwordInput.inputValues("12345678");
        inputSpecification.setValuesInForm(signInForm)
                .beforeClickElement("button").withText("Sign in");

        Form signUpForm = new Form();
        FormInput firstNameInput = signUpForm.inputField(FormInput.InputType.TEXT,
                new Identification(Identification.How.name, "crawljax_user_first_name"));
        firstNameInput.inputValues("foo");
        FormInput lastNameInput = signUpForm.inputField(FormInput.InputType.TEXT,
                new Identification(Identification.How.name, "crawljax_user_last_name"));
        lastNameInput.inputValues("bar");
        FormInput usernameInputSignUp = signUpForm.inputField(FormInput.InputType.EMAIL,
                new Identification(Identification.How.name, "crawljax_user_email"));
        usernameInputSignUp.inputValues("foo@bar.com");
        FormInput passwordInputSignUp = signUpForm.inputField(FormInput.InputType.PASSWORD,
                new Identification(Identification.How.name, "crawljax_user_password"));
        passwordInputSignUp.inputValues("foobar123");
        FormInput passwordInputConfirmationSignUp = signUpForm.inputField(FormInput.InputType.PASSWORD,
                new Identification(Identification.How.name, "crawljax_user_password_confirmation"));
        passwordInputConfirmationSignUp.inputValues("foobar123");
        inputSpecification.setValuesInForm(signUpForm)
                .beforeClickElement("button").withText("Sign up");

        Form boardForm = new Form();
        FormInput boardNameInput = boardForm.inputField(FormInput.InputType.TEXT,
                new Identification(Identification.How.id, "board_name"));
        boardNameInput.inputValues("board","new board","just a board","board name","delivering the goods");
        inputSpecification.setValuesInForm(boardForm)
                .beforeClickElement("button").withText("Create board");

        Form addNewMembersForm = new Form();
        FormInput memberEmailInput = addNewMembersForm.inputField(FormInput.InputType.EMAIL,
                new Identification(Identification.How.xpath,
                        "/html[1]/body[1]/main[1]/div[1]/div[1]/div[1]/div[1]/header[1]/ul[1]/span[1]/li[2]/ul[1]/li[1]/form[1]/input[1]".toUpperCase()));
        memberEmailInput.inputValues("john@phoenix-trello.com","foo@bar.com");
        inputSpecification.setValuesInForm(addNewMembersForm)
                .beforeClickElement("button").withText("Add member");

        Form listForm = new Form();
        FormInput listNameInput = listForm.inputField(FormInput.InputType.TEXT,
                new Identification(Identification.How.id, "list_name"));
        listNameInput.inputValues("list","new list","just a list","list name","standard tuning");
        inputSpecification.setValuesInForm(listForm)
                .beforeClickElement("button").withText("Save list");

        Form updateListForm = new Form();
        FormInput updateListNameInput = updateListForm.inputField(FormInput.InputType.TEXT,
                new Identification(Identification.How.id, "list_name"));
        updateListNameInput.inputValues("updated list","updated new list","just updated a list","updated list name","phantom of the opera");
        inputSpecification.setValuesInForm(updateListForm)
                .beforeClickElement("button").withText("Update list");

        Form addNewCardForm = new Form();
        FormInput newCardInput = addNewCardForm.inputField(FormInput.InputType.TEXTAREA,
                new Identification(Identification.How.id, "card_name"));
        newCardInput.inputValues("card", "new card", "just a card", "card name", "surfing with the alien");
        inputSpecification.setValuesInForm(addNewCardForm)
                .beforeClickElement("button").withText("Add");

        Form editCardForm = new Form();
        FormInput titleInput = editCardForm.inputField(FormInput.InputType.TEXT,
                new Identification(Identification.How.xpath,
                        "/html[1]/body[1]/main[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/header[1]/form[1]/input[1]".toUpperCase()));
        titleInput.inputValues("updated card", "updated new card", "just updated a card", "updated card name", "if I could fly");
        FormInput descriptionInput = editCardForm.inputField(FormInput.InputType.TEXTAREA,
                new Identification(Identification.How.xpath,
                        "/html[1]/body[1]/main[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/header[1]/form[1]/textarea[1]".toUpperCase()));
        descriptionInput.inputValues("description", "new description", "just a description", "long description", "crowd chant");
        inputSpecification.setValuesInForm(editCardForm)
                .beforeClickElement("button").withText("Save card");

        Form cardCommentForm = new Form();
        FormInput commentInput = cardCommentForm.inputField(FormInput.InputType.TEXTAREA,
                new Identification(Identification.How.xpath,
                        "/html[1]/body[1]/main[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/form[1]/div[2]/textarea[1]".toUpperCase()));
        commentInput.inputValues("comment", "new comment", "just a comment", "long comment", "what happens next");
        inputSpecification.setValuesInForm(cardCommentForm)
                .beforeClickElement("button").withText("Save comment");

        builder.crawlRules().setInputSpec(inputSpecification);

        builder.crawlRules().setDisableIdAndNameIdentification(true);

        builder.setHandleSameFormInputsOncePerState(true);



        return builder;

    }

    @Override
    public SuiteGeneratorConfig getSuiteGeneratorConfig() {

        SuiteGeneratorConfig suiteGeneratorConfig = this.testSuiteGeneratorCommonConfig(url, waitTimeAfterReload);
        suiteGeneratorConfig.setScriptNameToInclude("application");
        suiteGeneratorConfig.setSourcemapURL("http://localhost:4000/js/application.js.map");
        suiteGeneratorConfig.setSrcCodeFolder("web/static/js");
        suiteGeneratorConfig.setFiredElementStrategy(false);

        return suiteGeneratorConfig;
    }

    @Override
    public DependencyGraphExtractionConfig getDependencyGraphExtractionConfig() {
        String dependencyGraphOptimized = "1 10 000 0011 00010 000000 0000000 00010000 101000010 0000001000 10010010000 000000000000 0000000000000 10000000000000 000000000010000 0000000000000000 01001011001100000 111000010000000000 0000000001001000000 10010000000000000000 000100001000100010000 1000000001000000000000 00010001000000000000000 001001100000000000000000 1011001100000000000000100 00000100000000000000000000 000010000000000000000000000 0000000101000000001000000000 11010100000000010000100000000 011000010000000010000000000000 0010111000100000000000100000001 01011100100000000000000000000001 111010001011000000100000000001000 0101000111000000000000000001000000 10100010000001000000100000100000000 011000110000010110100000000000000000 0000011100010000100000001000000000000 11010101001100100000101010101011000000 000001100010000000000001110001000000000 1010000000000000100010001000000000000000 01010001010100100000000000010000001000001 010000010100101000001010000000100000000000 0110010101111100101000000010000000000100000 00000010010001110000000000000000000000000000 100100000000001000000000000000000000000000000 0001000010000000010000000000000000000000000011 01011101010000000001000010101000000000000000011 010000000000000010000010010000000000000000000000 1000110000000011100010001100000100000000000000001 00001010000110001000000000000000000100000000000000 001000010100100010001000100000000000000000000000000 0010000000001100101000100000000000000000000000000010";

        DependencyGraphExtractionConfig dependencyGraphExtractionConfig = new DependencyGraphExtractionConfig();
        dependencyGraphExtractionConfig.setParetoFrontSolution(dependencyGraphOptimized);
        // window strategy
//        dependencyGraphExtractionConfig.setFixedMinimizedTestSuite("11101000101100100000100110000000000011000000000011000");
        // one by one strategy
        dependencyGraphExtractionConfig.setFixedMinimizedTestSuite("11111111111111100000100110000000000011000000000011000");


        return dependencyGraphExtractionConfig;
    }
}
